export const GET_USER="GET_USER"
export const GET_USER_SUCCESS="GET_USER_SUCCESS"
export const GET_USER_FALL="GET_USER_FALL"

export const CREATE_USER="CREATE_USER"
export const CREATE_USER_SUCCESS="CREATE_USER_SUCCESS"
export const CREATE_USER_FALL="CREATE_USER_FALL"

export const GET_USER_DATA="GET_USER_DATA"
export const GET_USER_DATA_SUCCESS="GET_USER_DATA_SUCCESS"
export const GET_USER_DATA_FALL="GET_USER_DATA_FALL"


export const ADD_NOTE="ADD_NOTE"
export const ADD_NOTE_FALL="ADD_NOTE_FALL"

export const UPDATE_NOTE="UPDATE_NOTE"
export const UPDATE_NOTE_FALL="UPDATE_NOTE_FALL"

export const DELETE_NOTE="DELETE_NOTE"
export const DELETE_NOTE_FALL="DELETE_NOTE_FALL"

export const CLEAR_ERRORS="CLEAR_ERRORS"